CREATE SEQUENCE IF NOT EXISTS SEQ_CONTACT_ID;

CREATE TABLE IF NOT EXISTS CONTACT (
    CONTACT_ID INTEGER DEFAULT nextval('SEQ_CONTACT_ID'),
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SECRET VARCHAR(100),
)
